name: Deploy NestJS to EC2

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Lint code
      run: npm run lint
      
    - name: Build application
      run: npm run build
      
    - name: Run tests
      run: npm run test
      
    - name: Create .env file
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env
      
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Navigate to app directory
          cd ~/app
          
          # Pull latest code
          git pull origin main
          
          # Install dependencies
          npm ci
          
          # Build the app
          npm run build
          
          # Copy the environment file
          echo "${{ secrets.ENV_FILE }}" > .env
          
          # Restart the application using PM2
          pm2 restart nestjs-app || pm2 start dist/main.js --name nestjs-app
          
          # Optionally clear npm cache
          npm cache clean --force
          
          echo "Deployment completed successfully!"

    - name: Verify deployment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Check if app is running
          pm2 status
          
          # Output app logs
          pm2 logs nestjs-app --lines 10

